name: "FactorsDB"
description: "Database of browser-based psychology experiments for teaching"

url: "jodeleeuw.github.io/factorsdb"
baseurl: "/factorsdb"

paginate: 10

markdown: rdiscount
permalink: pretty

collections:
  experiments:
    output: true
    categories: ['attention', 'perception', 'memory']

defaults:
  - scope:
      path: ""
      type: experiments
    values:
      layout: experiment
