name: "FactorsDB"
description: "Database of browser-based psychology experiments for teaching"

url: "www.factorsdb.org"
baseurl: ""

paginate: 10

markdown: rdiscount
permalink: pretty

collections:
  experiments:
    output: true
    categories: ['attention', 'perception', 'memory', 'executive function']

defaults:
  - scope:
      path: ""
      type: experiments
    values:
      layout: experiment
